# Generated by Django 4.1.3 on 2023-03-05 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friend", "0002_friend_friend_friend_user_alter_friend_last_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friend",
            old_name="last_updated",
            new_name="update_dt",
        ),
    ]
