# Generated by Django 4.1.3 on 2023-03-05 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("friend", "0003_rename_last_updated_friend_update_dt"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend",
            name="create_dt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
