# Generated by Django 4.1.3 on 2026-02-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_friend_create_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
