# Generated by Django 4.1.3 on 2022-12-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0002_alter_expense_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=999999999999),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("UP", "Unpaid"), ("P", "Paid")], max_length=2
                    ),
                ),
            ],
        ),
    ]
