# Generated by Django 4.1.3 on 2022-12-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0004_expense_shared_expense_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="shared_expense_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_expenses",
                to="expense.sharedexpense",
            ),
        ),
    ]
