# Generated by Django 4.1.3 on 2022-12-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0006_rename_shared_expense_id_expense_shared_expense"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="shared_expense",
        ),
        migrations.AddField(
            model_name="sharedexpense",
            name="expense_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="expense.expense",
            ),
            preserve_default=False,
        ),
    ]
