# Generated by Django 4.1.3 on 2022-12-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0007_remove_expense_shared_expense_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sharedexpense",
            old_name="expense_id",
            new_name="expense",
        ),
    ]
