# Generated by Django 4.1.3 on 2022-12-08 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0008_rename_expense_id_sharedexpense_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedexpense",
            name="expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_expenses",
                to="expense.expense",
            ),
        ),
    ]
