# Generated by Django 4.1.3 on 2023-01-27 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expense", "0011_expense_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="user_id",
        ),
        migrations.AddField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sharedexpense",
            name="shared_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
