# Generated by Django 4.1.3 on 2023-03-04 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0012_remove_expense_user_id_expense_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="last_updated",
            new_name="update_dt",
        ),
        migrations.RenameField(
            model_name="sharedexpense",
            old_name="shared_user",
            new_name="loaner",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="date_time",
        ),
        migrations.AddField(
            model_name="expense",
            name="create_dt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sharedexpense",
            name="create_dt",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sharedexpense",
            name="update_dt",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
