# Generated by Django 4.1.3 on 2023-08-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0013_rename_user_expense_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="is_shared",
        ),
    ]
