# Generated by Django 4.1.3 on 2026-02-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0014_remove_expense_is_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sharedexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
